In [33]:
import pandas as pd
import pandas as pd
import preprocessing_tools as pr
from cleanedNames import KeyProc
cn = KeyProc()
import warnings
warnings.filterwarnings('ignore')
import os

In [9]:
!ls -l data/lenta/*.bz2

-rw-rw-r-- 1 midzay midzay  6371216 фев 26 07:36 data/lenta/Biznes.csv.bz2
-rw-rw-r-- 1 midzay midzay 16417997 фев 26 07:36 data/lenta/Internet_i_SMI.csv.bz2
-rw-rw-r-- 1 midzay midzay 19562889 фев 26 07:36 data/lenta/Sport.csv.bz2

In [10]:
!ls -l data/interfax/*.bz2

-rw-rw-r-- 1 midzay midzay 17385899 фев 26 07:35 data/interfax/Biznes.csv.bz2
-rw-rw-r-- 1 midzay midzay 12991336 фев 26 07:35 data/interfax/Internet_i_SMI.csv.bz2
-rw-rw-r-- 1 midzay midzay 29993874 фев 26 07:35 data/interfax/Sport.csv.bz2

In [58]:
LENTAPATH = "data/lenta/"
INTERFAXPATH='data/interfax/'

df_lenta = pd.read_csv(LENTAPATH+'Biznes.csv.bz2')

In [62]:
df_lenta.sample(5)

,1914-lenta/,url,edition,topics,title,text,topic
1438,2005-09-05 12:00:00,https://lenta.ru/news/2005/09/05/poultry/,NaN,Мир,"""Катрина"" оставит Россию без ""ножек Буша""","Ураган ""Катрина"", разрушивший часть южного поб...",Бизнес
12381,2017-01-30 12:00:00,https://lenta.ru/news/2017/01/30/starbucks_bez...,NaN,Бизнес / Бизнес,Starbucks пообещал трудоустроить 10 тысяч беже...,Сеть кофеен Starbucks планирует нанять на рабо...,Бизнес
2041,2006-01-16 12:00:00,https://lenta.ru/news/2006/01/16/izh/,NaN,Россия,"""Иж-Авто"" сократил производство на 45-процентов",По итогам 2005 году объемы производства на пре...,Бизнес
4647,2010-11-11 12:00:00,https://lenta.ru/news/2010/11/11/tube/,NaN,Экономика,"Россия лишит нефти трубопровод ""Одесса-Броды""","""Транснефть"" с 2011 года отказывается от испол...",Бизнес
7774,2015-04-13 12:00:00,https://lenta.ru/news/2015/04/13/s400/,NaN,Силовые структуры,Китай заключил контракт на закупку С-400,Китай заключил с «Рособоронэкспортом» контракт...,Бизнес

In [24]:
df_lenta = df_lenta.rename(columns={'1914-lenta/':'date','topic':'predict','topics':'topic',})
df_lenta = df_lenta[['date','topic','text','predict']]
df_lenta.head()

,date,topic,text,predict
0,1999-10-06 12:00:00,Экономика,"Как сообщает агентство РИА ""Новости"", главная ...",Бизнес
1,1999-10-11 12:00:00,Экономика,"Автомобили - единственный род продукции, котор...",Бизнес
2,1999-10-11 12:00:00,Экономика,"Как ссобщает газета ""Время MN"" премьер-министр...",Бизнес
3,1999-10-13 12:00:00,Экономика,Компания Planet Hollywood закрыла в минувший в...,Бизнес
4,1999-10-13 12:00:00,Экономика,Концерн Philip Morris Co. во вторник открыл ин...,Бизнес

In [16]:
df_interfax = pd.read_csv(INTERFAXPATH+'Biznes.csv.bz2')

In [17]:
df_interfax.head()

,date,topic,text,predict,text_new,lemmatized_text
0,2008-02-11 18:07:00,"""Экономика""","- Вечерние торжества по случаю 15-летия \""Газ...",Бизнес,вечерние торжества по случаю летия \газпрома\ ...,"['вечерний', 'торжество', 'случай', 'летие', '..."
1,2008-02-20 06:05:00,"""Экономика""",- Государство с 2011 года ежегодно будет выде...,Бизнес,государство с года ежегодно будет выделять м...,"['государство', 'ежегодно', 'выделять', 'милли..."
2,2008-02-21 10:58:00,"""Экономика""",- Societe Generale второй по рыночной капитал...,Бизнес,societe generale второй по рыночной капитализа...,"['societe', 'generale', 'рыночный', 'капитализ..."
3,2008-02-27 13:36:00,"""Экономика""",- Новая схема поставок газа на Украину о кото...,Бизнес,новая схема поставок газа на украину о которой...,"['новый', 'схема', 'поставка', 'газа', 'украин..."
4,2008-02-29 14:45:00,"""Экономика""","- ОАО \""Вымпелком\"" завершило сделку по слиян...",Бизнес,оао \вымпелком\ завершило сделку по слиянию св...,"['оао', 'вымпелком', 'завершить', 'сделка', 'с..."

#### На данный момент структура датасетов у нас разная, поэтому приведем ленту к  виду интрефакса

In [25]:
df_lenta['text_new'] = df_lenta.text.apply(pr.clean_text)
df_lenta.text_new = df_lenta.text_new.apply(cn.replaceKeywords)
df_lenta['lemmatized_text'] = df_lenta.text_new.apply(pr.lemmatization)
df_lenta.to_csv(LENTAPATH+'out/Biznes.csv.bz2',index=False,compression='bz2')

FileNotFoundError: [Errno 2] No such file or directory: 'data/lenta//out/Biznes.csv.bz2'

In [28]:
df_lenta.head()

,date,topic,text,predict,text_new,lemmatized_text
0,1999-10-06 12:00:00,Экономика,"Как сообщает агентство РИА ""Новости"", главная ...",Бизнес,как сообщает агентство риа новости главная тем...,"[агентство, риа, новость, главный, тема, встре..."
1,1999-10-11 12:00:00,Экономика,"Автомобили - единственный род продукции, котор...",Бизнес,автомобили единственный род продукции который...,"[автомобиль, единственный, род, продукция, про..."
2,1999-10-11 12:00:00,Экономика,"Как ссобщает газета ""Время MN"" премьер-министр...",Бизнес,как ссобщает газета время mn премьерминистр вл...,"[ссобщаета, газета, mn, премьерминистр, владим..."
3,1999-10-13 12:00:00,Экономика,Компания Planet Hollywood закрыла в минувший в...,Бизнес,компания planet hollywood закрыла в минувший в...,"[planet, hollywood, закрыть, минувший, рестора..."
4,1999-10-13 12:00:00,Экономика,Концерн Philip Morris Co. во вторник открыл ин...,Бизнес,концерн philip morris co во вторник открыл инт...,"[концерн, philip, morris, co, открыть, интерне..."

In [29]:
df_all = pd.concat([df_lenta,df_interfax],axis=0,ignore_index=True)

In [43]:
print(df_lenta.shape,df_interfax.shape,df_all.shape)
print(df_lenta.shape[0]+df_interfax.shape[0]==df_all.shape[0])

(13374, 6) (10909, 6) (24283, 6)
True

In [32]:
df_all.to_csv('data/all/Biznes.csv.bz2',index=False,compression='bz2')

In [44]:
files = list(os.walk(LENTAPATH))[0][2]
processed = ['Biznes.csv.bz2']

Запускаем оставшиеся файлы на автомате

In [55]:
for file in files:
    if file not in processed:
        df_lenta = pd.read_csv(LENTAPATH+file)
        df_lenta = df_lenta.rename(columns={'1914-lenta/':'date','topic':'predict','topics':'topic',})
        df_lenta = df_lenta[['date','topic','text','predict']]
        df_lenta['text_new'] = df_lenta.text.apply(pr.clean_text)
        df_lenta.text_new = df_lenta.text_new.apply(cn.replaceKeywords)
        df_lenta['lemmatized_text'] = df_lenta.text_new.apply(pr.lemmatization)
        df_lenta.to_csv(LENTAPATH+'out/'+file,index=False,compression='bz2')
        df_interfax = pd.read_csv(INTERFAXPATH+file)
        df_all = pd.concat([df_lenta,df_interfax],axis=0,ignore_index=True)
        print(file ,df_lenta.shape[0]+df_interfax.shape[0]==df_all.shape[0])
        df_all.to_csv('data/all/'+file,index=False,compression='bz2')
        processed.append(file)

Internet_i_SMI.csv.bz2 True
Sport.csv.bz2 True

 В итоге мы имее три файла с разными  рубриками с объеденеными датасетами интерфакса и ленты

In [57]:
df_all.sample(10)

,date,topic,text,predict,text_new,lemmatized_text
43284,2015-10-21 12:00:00,Спорт / Футбол,Московский ЦСКА и английский «Манчестер Юнайте...,Спорт,московский цска и английский манчестер юнайтед...,"[московский, цска, английский, манчестер, юнай..."
30214,2011-10-12 12:00:00,Спорт,"Менеджер братьев Кличко Бернд Бенте заявил, чт...",Спорт,менеджер братьев кличко бернд бенте заявил что...,"[менеджер, брат, кличко, бернд, бента, бой, ви..."
40955,2014-05-05 12:00:00,Спорт / Футбол,Александр Цыганков покинул пост главного трене...,Спорт,александр цыганков покинул пост главного трене...,"[александр, цыганков, покинуть, пост, главный,..."
87636,2014-08-08 15:12:00,"""Спорт""","- Московский \""Локомотив\"" встретится с кипр...",Спорт,московский \локомотив\ встретится с кипрской к...,"['московский', 'локомотив', 'встретиться', 'ки..."
33943,2012-10-26 12:00:00,Спорт,"Главный тренер голландского ""Твенте"" Стив Макл...",Спорт,главный тренер голландского твенте стив_маклар...,"[главный, тренер, голландский, твента, стив_ма..."
11332,2007-09-10 12:00:00,Спорт,"Врачи итальянского ""Милана"" признали, что пост...",Спорт,врачи итальянского милана признали что постави...,"[врач, итальянский, милан, признать, поставить..."
20138,2009-08-17 12:00:00,Спорт,"Английский боксер Дэвид Хэй заявил, что братья...",Спорт,английский боксер дэвид_хэй заявил что братья ...,"[английский, боксёр, дэвид_хэй, брат, кличко, ..."
99007,2017-05-11 17:16:00,"""Спорт""",- Контрольно-дисциплинарный комитет Российско...,Спорт,контрольнодисциплинарный комитет российского ф...,"['контрольнодисциплинарный', 'комитет', 'росси..."
62221,2008-08-22 12:52:00,"""Спорт""",- Сборная России по синхронному плаванию (Ерм...,Спорт,сборная россии по синхронному плаванию ермаков...,"['сборная', 'россия', 'синхронный', 'плавание'..."
47260,2016-12-08 12:00:00,Спорт / Футбол,«Зенит» будет платить не более одного рубля в ...,Спорт,зенит будет платить не более одного рубля в го...,"[зенит, платить, рубль, аренда, футбольный, ст..."